### ISSUE TITLE
Add parsing of *.prod files

### ISSUE THREAD

**Issue by saschagrunert** [SUSE/container-suseconnect#27]
The idea is to parse the module names from the `*.prod` files within `/etc/products.d/`, like these:

```
sle-module-basesystem.prod
sle-module-containers.prod
sle-module-live-patching.prod
sle-module-server-applications.prod
```

This would allow building images with kiwi without setting the `ADDITIONAL_MODULES` environment variable.

**Comment by jvanz** [comment]
Is the idea read the prod file just to get the names or use some data from the files as well?
Should the `ADDITIONAL_MODULES` environment variable be removed? Should we allow the user enables a module which does not have the `prod` file?

**Comment by saschagrunert** [comment]
> Is the idea read the prod file just to get the names or use some data from the files as well?

I think it's all about the names.

> Should the `ADDITIONAL_MODULES` environment variable be removed?

I would still let them in since people could already rely on it.

> Should we allow the user enables a module which does not have the `prod` file?

Yeah why not? :)

**Comment by jvanz** [comment]
We can close this one! =D

**Comment by saschagrunert** [comment]
Thanks!
