### ISSUE TITLE
x509 issue when creating SLES12SP4 Container Image

### ISSUE THREAD

**Issue by xinzweb** [SUSE/container-suseconnect#36]
We experienced x509 certificate issue on the SLES12SP4 docker container, with 2.0.0 release of the container-suseconnect.

```
$ update-ca-certificates 
$ container-suseconnect 
2019/10/23 18:07:59 Installed product: SLES-12.4-x86_64
2019/10/23 18:07:59 Registration server set to https://smt-gce.susecloud.net
2019/10/23 18:07:59 Get https://smt-gce.susecloud.net/connect/subscriptions/products?arch=x86_64&identifier=SLES&version=12.4: x509: issuer name does not match subject from issuing certificate

$ container-suseconnect --version
container-suseconnect version 2.0.0
```

However, when we use openssl, there is no trouble connecting to the smt:

```
$ openssl s_client -connect smt-gce.susecloud.net:443
```

We are not sure whether this is related to https://github.com/SUSE/container-suseconnect/issues/19.

For additional details, please check the thread at https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/gce-discussion/9H06B-WZ1VA/yuy2RLAdDAAJ

**Comment by xinzweb** [comment]
We researched further and found a known x509 issue at https://github.com/golang/go/issues/31440. Basically, there is a name mismatch between the certificates, if the encoding of the subject and issuer are mismatched.

We debugged the further on the verify.go, and found the following:

```
(gdb) p child.RawIssuer
$7 = {
  array = 0xc000108029 "0\201\217\061\v0\t\006\003U\004\006\023\002DE1\020\060\016\006\003U\004\b\f\aBavaria1\022\060\020\006\003U\004\a\f\tNuremberg1\r0\v\006\003U\004\n\f\004SUSE1\f0\n\006\003U\004\v\f\003CSM1\r0\v\006\003U\004\003\f\004SUSE1.0,\006\t*\206H\206\367\r\001\t\001\026\037suse-public-cloud@susecloud.net0\036\027\r190329165041Z\027\r290326165041Z0\201\305\061\v0\t\006\003U\004\006\023\002DE1\020\060\016\006\003"..., len = 146, cap = 1751}

(gdb) p c.RawSubject
$8 = {
  array = 0xc0002cb259 "0\201\217\061\v0\t\006\003U\004\006\023\002DE1\020\060\016\006\003U\004\b\023\aBavaria1\022\060\020\006\003U\004\a\023\tNuremberg1\r0\v\006\003U\004\n\023\004SUSE1\f0\n\006\003U\004\v\023\003CSM1\r0\v\006\003U\004\003\023\004SUSE1.0,\006\t*\206H\206\367\r\001\t\001\026\037suse-public-cloud@susecloud.net0\202\001\"0\r\006\t*\206H\206\367\r\001\001\001\005", len = 146, cap = 1139}
```

Indeed the encoding is different. For example, the `\f` became `\023` mismatched between those two.

**Comment by saschagrunert** [comment]
Hey @xinzweb, :wave: thanks for the report. Do you see anything on our side what we can do to resolve the issue? Maybe a rebuild with go 1.13?

**Comment by ikapelyukhin** [comment]
Hello, @xinzweb. Thanks for the report and for providing the details -- this information was very helpful.

I've put together a script to print out all strings in the certificate and their respective ASN data types:

```ruby
#!/usr/bin/env ruby

require 'openssl'

def print_asn_strings(obj, depth = 0)
  if obj.respond_to? :each
    obj.each do |item|
      print_asn_strings(item, depth + 1)
    end
  else
    printf("%-40s %s\n", obj.value, obj.class) if (
      obj.class.to_s.match(/String/) &&
      obj.class != OpenSSL::ASN1::BitString
    )
  end
end

raise "Usage: #{$0} cert-file.crt" unless ARGV[0]

certificate = OpenSSL::X509::Certificate.new(File.read(ARGV[0]))
asn1 = OpenSSL::ASN1.decode(certificate.to_der)
print_asn_strings(asn1)
```

Our certificates indeed have different ASN data types. RMT CA:

```
$> ./print_asn_strings.rb rmt-ca.crt
DE                                       OpenSSL::ASN1::PrintableString
Bavaria                                  OpenSSL::ASN1::PrintableString
Nuremberg                                OpenSSL::ASN1::PrintableString
SUSE                                     OpenSSL::ASN1::PrintableString
CSM                                      OpenSSL::ASN1::PrintableString
SUSE                                     OpenSSL::ASN1::PrintableString
suse-public-cloud@susecloud.net          OpenSSL::ASN1::IA5String
```

RMT server certificate:

```
$> ./print_asn_strings.rb rmt-server.crt
DE                                       OpenSSL::ASN1::PrintableString
Bavaria                                  OpenSSL::ASN1::UTF8String
Nuremberg                                OpenSSL::ASN1::UTF8String
SUSE                                     OpenSSL::ASN1::UTF8String
CSM                                      OpenSSL::ASN1::UTF8String
SUSE                                     OpenSSL::ASN1::UTF8String
suse-public-cloud@susecloud.net          OpenSSL::ASN1::IA5String
```

Different data types didn't cause issues with openssl, it seems that Go implementation is pickier in this regard.

To fix the issue we'll either have to re-issue the certificates, or Go implementation of X509 cert verification has to be encoding-agnostic upstream.

Thanks, Ivan.

**Comment by ikapelyukhin** [comment]
We'll re-issue server certificates and enforce same ASN.1 data type everywhere.
I'll post an update once the new certificates are deployed.

**Comment by xinzweb** [comment]
We will be looking forward to the new certificate then. Thanks.

**Comment by ikapelyukhin** [comment]
> We will be looking forward to the new certificate then. Thanks.

@xinzweb we have deployed new certificates to all RMT servers in all regions. Please let me know if the issue still persists.

**Comment by rhafer** [comment]
I'll close this. The issue seems to be fixed since a few months already.
