### ISSUE TITLE
Problem retrieving the repository index file

### ISSUE THREAD

**Issue by bradfordboyle** [SUSE/container-suseconnect#37]
I am running SLES 12SP4 in VM on Google Compute Engine (GCE) and following the documentation for [Creating Custom Images][0]. When I try to build the following Dockerfile

```docker
FROM registry.suse.com/suse/sles12sp4:latest

RUN zypper ref -s
RUN zypper -n in vim
```

I get the following error:

```sh
Problem retrieving the repository index file for service 'container-suseconnect-zypp':
[container-suseconnect-zypp|file:/usr/lib/zypp/plugins/services/container-suseconnect-zypp]
```

and see the following in the log file:

```
2019/10/29 03:07:27 Installed product: SLES-12.4-x86_64
2019/10/29 03:07:27 Warning: Unknown key 'language'
2019/10/29 03:07:27 Registration server set to https://smt-gce.susecloud.net
2019/10/29 03:07:27 Unexpected error while retrieving products with regCode : 401 Unauthorized
2019/10/29 03:07:27 Unexpected error while retrieving products with regCode : 401 Unauthorized
```

This error message is coming from [products.go][1] which is attempting to make an HTTP `GET` to `/connect/subscriptions/products` _without_ an authorization token (c.f., the comment about SMT does not need regcode). However, accoding the to the [v4 API docs][2] it is confusing about whether a token is needed:

> all endpoints on this level of the subscription's token (registration code) is used for authentication. This should be sent as an authorization header

but further down it says:

> A registration code is not required for authentication by RMT or SMT

If I use `curl` to make the equivalent call

```sh
$ curl -X GET "https://smt-gce.susecloud.net/connect/subscriptions/products?identifier=SLES&version=12&arch=x86_64" -H "accept: application/json"
HTTP Token: Access denied.
```

I decided to try re-building `container-suseconnect` with the following changes:

1. Change URL path from `/connect/subscriptions/products` to `/connect/systems/products` in [products.go][3]
2. Include basic auth credentials for the HTTP `GET` to `/connect/subscriptions/products` in [products.go][4]

I then had to change the return type for the following functions from `[]Product` to `Product`

1. [`parseProducts`][5]
2. [`requestProductsFromRegCode`][6]

After replacing `/usr/lib/zypp/plugins/services/container-suseconnect-zypp` with my modified binary, I was able to run `zypper ref -s` and `zypper in -n vim` inside of a container although I was prompted for my basic auth credentials twice.

[0]: https://documentation.suse.com/sles/12-SP4/single-html/SLES-dockerquick/#docker-building-images
[1]: https://github.com/SUSE/container-suseconnect/blob/18695994bb30e10c2b4379ff1265ea12e80e856b/internal/products.go#L74-L118
[2]: https://scc.suse.com/connect/v4/documentation#/subscriptions/get_subscriptions_products
[3]: https://github.com/bradfordboyle/container-suseconnect/blob/47034be1b8fbc15790a4dcc41b9fb6dd6398d2c0/internal/products.go#L96
[4]: https://github.com/bradfordboyle/container-suseconnect/blob/47034be1b8fbc15790a4dcc41b9fb6dd6398d2c0/internal/products.go#L85
[5]: https://github.com/bradfordboyle/container-suseconnect/blob/47034be1b8fbc15790a4dcc41b9fb6dd6398d2c0/internal/products.go#L52
[6]: https://github.com/bradfordboyle/container-suseconnect/blob/47034be1b8fbc15790a4dcc41b9fb6dd6398d2c0/internal/products.go#L74-L75

**Comment by saschagrunert** [comment]
Hey @bradfordboyle, thank you for the detailed issue report. :pray: We'll check if we have to adjust the authentication further to seamlessly integrate with `smt-gce.susecloud.net`. If you want, then you could also prepare a PR if you think that you've fixed the issue with your changes.

**Comment by rhafer** [comment]
> However, accoding the to the [v4 API docs](https://scc.suse.com/connect/v4/documentation#/subscriptions/get_subscriptions_products) it is confusing about whether a token is needed:

agreed

> > all endpoints on this level of the subscription's token (registration code) is used for authentication. This should be sent as an authorization header
> 
> but further down it says:
> 
> > A registration code is not required for authentication by RMT or SMT

As far as I understand the rmt sources it requires a token to be present for `/connect/subscriptions/products`

https://github.com/SUSE/rmt/blob/master/app/controllers/api/connect/v4/subscriptions/products_controller.rb#L3

So switching to `/connect/systems/products` like you did seems like the correct approach. I'll check back with RMT folks.

**Comment by ikapelyukhin** [comment]
@rjschwei ping for interest. Seems like "flipping the switch" will do funny things to this project.

**Comment by acmnu** [comment]
It looks like I have the same issue, when I try to build 15sp1 container on 15sp1 host. So it is not a trouble described in documentation with host and container OS mismatch.

**Comment by rhafer** [comment]
> It looks like I have the same issue, when I try to build 15sp1 container on 15sp1 host. So it is not a trouble described in documentation with host and container OS mismatch.

@acmnu Please check which version of container-suseconnect is installed inside your base container by running  (`rpm -q container-suseconnect`) inside the container.

**Comment by acmnu** [comment]
Sorry, seems my trouble is not related to that case. I got HTTP 401, but in zypper, not in container-suseconnect itself.

I have SLES 15 SP1 in GCE with support (zypper is OK on host):

```
# rpm -qa | grep sles-release
sles-release-15.1-66.1.x86_64
# docker run -it --rm  registry.suse.com/suse/sle15:latest rpm -q container-suseconnect
container-suseconnect-2.2.0-4.9.3.x86_64
```

I trying to build some test docker image. But I have to add certificate or I got x509. So I made some changes. BTW, for some reason smt-gce.susecloud.net is not resolved, and I have to pass this information to container over add-host. That is madness in GCE. 
```
# cat Dockerfile
FROM registry.suse.com/suse/sle15:latest

ENV ADDITIONAL_MODULES sle-module-desktop-applications,sle-module-development-tools

ADD http://smt-gce.susecloud.net/smt.crt /etc/pki/trust/anchors/smt.crt
RUN update-ca-certificates
RUN container-suseconnect

RUN zypper --gpg-auto-import-keys ref -s
RUN zypper -n in gvim

# docker build -t test1 \
> --add-host="smt-gce.susecloud.net:192.158.29.172" \
> .
Sending build context to Docker daemon  14.85kB
Step 1/7 : FROM registry.suse.com/suse/sle15:latest
 ---> 91f2bad53a20
Step 2/7 : ENV ADDITIONAL_MODULES sle-module-desktop-applications,sle-module-development-tools
 ---> Using cache
 ---> 4fd55addbbcb
Step 3/7 : ADD http://smt-gce.susecloud.net/smt.crt /etc/pki/trust/anchors/smt.crt
Downloading [==================================================>]  1.891kB/1.891kB
 ---> Using cache
 ---> 293e850276b3
Step 4/7 : RUN update-ca-certificates
 ---> Using cache
 ---> 50c9c64805e1
Step 5/7 : RUN container-suseconnect
 ---> Using cache
 ---> 91263b5080c8
Step 6/7 : RUN zypper --gpg-auto-import-keys ref -s
 ---> Running in 341a38f50f23
Refreshing service 'container-suseconnect-zypp'.
Adding repository 'SLE-Module-Basesystem15-SP1-Debuginfo-Pool for sle-15-x86_64' [......done]
Adding repository 'SLE-Module-Basesystem15-SP1-Debuginfo-Updates for sle-15-x86_64' [......done]
Adding repository 'SLE-Module-Basesystem15-SP1-Pool for sle-15-x86_64' [......done]
Adding repository 'SLE-Module-Basesystem15-SP1-Source-Pool for sle-15-x86_64' [......done]
Adding repository 'SLE-Module-Basesystem15-SP1-Updates for sle-15-x86_64' [......done]
Adding repository 'SLE-Module-Desktop-Applications15-SP1-Debuginfo-Pool for sle-15-x86_64' [......done]
Adding repository 'SLE-Module-Desktop-Applications15-SP1-Debuginfo-Updates for sle-15-x86_64' [......done]
Adding repository 'SLE-Module-Desktop-Applications15-SP1-Pool for sle-15-x86_64' [......done]
Adding repository 'SLE-Module-Desktop-Applications15-SP1-Source-Pool for sle-15-x86_64' [......done]
Adding repository 'SLE-Module-Desktop-Applications15-SP1-Updates for sle-15-x86_64' [......done]
Adding repository 'SLE-Module-DevTools15-SP1-Debuginfo-Pool for sle-15-x86_64' [......done]
Adding repository 'SLE-Module-DevTools15-SP1-Debuginfo-Updates for sle-15-x86_64' [......done]
Adding repository 'SLE-Module-DevTools15-SP1-Pool for sle-15-x86_64' [......done]
Adding repository 'SLE-Module-DevTools15-SP1-Source-Pool for sle-15-x86_64' [......done]
Adding repository 'SLE-Module-DevTools15-SP1-Updates for sle-15-x86_64' [......done]
Adding repository 'SLE-Module-Server-Applications15-SP1-Debuginfo-Pool for sle-15-x86_64' [......done]
Adding repository 'SLE-Module-Server-Applications15-SP1-Debuginfo-Updates for sle-15-x86_64' [......done]
Adding repository 'SLE-Module-Server-Applications15-SP1-Pool for sle-15-x86_64' [......done]
Adding repository 'SLE-Module-Server-Applications15-SP1-Source-Pool for sle-15-x86_64' [......done]
Adding repository 'SLE-Module-Server-Applications15-SP1-Updates for sle-15-x86_64' [......done]
Adding repository 'SLE-Product-SLES15-SP1-Debuginfo-Pool for sle-15-x86_64' [......done]
Adding repository 'SLE-Product-SLES15-SP1-Debuginfo-Updates for sle-15-x86_64' [......done]
Adding repository 'SLE-Product-SLES15-SP1-Pool for sle-15-x86_64' [......done]
Adding repository 'SLE-Product-SLES15-SP1-Source-Pool for sle-15-x86_64' [......done]
Adding repository 'SLE-Product-SLES15-SP1-Updates for sle-15-x86_64' [......done]
Adding repository 'SLE15-SP1-Installer-Updates for sle-15-x86_64' [......done]

All services have been refreshed.
Retrieving repository 'SLE-Module-Basesystem15-SP1-Pool for sle-15-x86_64' metadata [.
Authentication required for 'https://smt-gce.susecloud.net/repo/SUSE/Products/SLE-Module-Basesystem/15-SP1/x86_64/product/'
User Name: Authentication required for 'https://smt-gce.susecloud.net/repo/SUSE/Products/SLE-Module-Basesystem/15-SP1/x86_64/product/'
User Name: error]
Repository 'SLE-Module-Basesystem15-SP1-Pool for sle-15-x86_64' is invalid.
[container-suseconnect-zypp:SLE-Module-Basesystem15-SP1-Pool|https://smt-gce.susecloud.net/repo/SUSE/Products/SLE-Module-Basesystem/15-SP1/x86_64/product/] Valid metadata not found at specified URL
History:
 - [|] Error trying to read from 'https://smt-gce.susecloud.net/repo/SUSE/Products/SLE-Module-Basesystem/15-SP1/x86_64/product/'
 - Login failed. (https://smt-gce.susecloud.net/repo/SUSE/Products/SLE-Module-Basesystem/15-SP1/x86_64/product/content): The requested URL returned error: 401 Unauthorized
.....
```

I got 401 here in zypper. So it looks like I have to do a magic with credentials, but according by your documentation there is no need to do that when I am building sle15 on sle15.

**Comment by rhafer** [comment]
> So it looks like I have to do a magic with credentials, but according by your documentation there is no need to do that when I am building sle15 on sle15.

@acmnu That's right. As this seems to be a new problem, would you mind opening a new github issue for this?

**Comment by rhafer** [comment]
Closing this again. The new bug is tracked in https://github.com/SUSE/container-suseconnect/issues/41
