### ISSUE TITLE
Documentation for "Building images on non SLE distributions" is wrong in README.md

### ISSUE THREAD

**Issue by mwilck** [SUSE/container-suseconnect#48]
The given docker command line doesn't work. Instead of
```
--build-arg ADDITIONAL_MODULES=PackageHub
```
it should be
```
--build-arg ADDITIONAL_MODULES=sle-module-development-tools
```
In general, the syntax of the ADDITIONAL_MODULES parameter should be explained better.

**Comment by saschagrunert** [comment]
Hey @mwilck, thank you for opening the issue! :pray: Do you mind proposing a PR with the mentioned improvements?

**Comment by mwilck** [comment]
I can do this part, but not the documentation of `ADDITIONAL_MODULES`.

Suggestion for further improvement: add a default value for `ADDITIONAL_MODULES` in the Dockerfile.

**Comment by mwilck** [comment]
We really need a list of possible values for ADDITIONAL_MODULES somewhere.

**Comment by rhafer** [comment]
@mwilck `container-suseconnect --list-modules` is supposed to give that list I think. Or `SUSEConnect --list-extensions` (this one works of course only on a SLE host).

The list of possible modules depends on the Base Container (and maybe even on the used credentials) so there is not single list of truth that we can add to the documentation.

**Comment by mwilck** [comment]
Ok, I was unaware that `container-userconnect` was an executable I could all. Thanks. 

I still think a list of modules with there abbreviations should be documented somewhere, at least for the official SUSE modules. Also, it's not documented how to specify multiple modules (it seems to work by joining them with a comma, but the user needs to guess that).

**Comment by rhafer** [comment]
> Ok, I was unaware that `container-userconnect` was an executable I could call. Thanks.

You're welcome. (It's also documented in the README :-)  )

> I still think a list of modules with their abbreviations should be documented somewhere, at least for the official SUSE modules.

It might be possible to find that in the SCC. I don't know.

> Also, it's not documented how to specify multiple modules (it seems to work by joining them with a comma, but the user needs to guess that).

Yeah, I guess that makes sence.
