### ISSUE TITLE
Licensing requirements?

### ISSUE THREAD

**Issue by mayrstefan** [SUSE/container-suseconnect#55]
SLES is typically licensed per physical host/cpu or virtual machines? When we build or run SLES containers - what kind of licensing do we need? I already tried to get this information multiple times from SUSE and Rancher but never got a feedback that we could work with.

I guess the simple situation is when we build and run SLES containers on SLES hosts. But what kind of subscriptions do we need when we create or run such containers on non-SLES hosts? For example developer workstations running Windows or cloud container platforms. Do we just need one licensed SLES X machine to build and run an unlimited number of SLES X containers?

Using the registered zypper repositories from the host system - does this have any side effects if this machine is connected to SUSE Manager or Uyuni? Building a container image downloads packages that are not installed on the host which is registered to the repositories. What if we build containers with packages from different products like the HA extensions?

**Comment by alexandrevicenzi** [comment]
From the [BCI FAQ](https://www.suse.com/products/base-container-images/faq/):

> Do I need a subscription to use BCI?
>
> No, you can use them without a subscription. BCI can be used for free, just pulling from the registry, they are ready to be used with no support.
>
> BCI under an active SLE subscription provides a full support and access to SUSE repositories and a full set of tools and packages.

These and other questions are answered there.
